{% set name = "distoptica" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/distoptica-{{ version }}.tar.gz
  sha256: 9fdf27a593c16e9535c6155c49f7a4f6ee51828fefdcc33d43bf79f6bec1fc42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - fancytypes >=1.0.0
    - pytorch

test:
  imports:
    - distoptica
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/distoptica/
  summary: Python library for modelling optical distortions.
  dev_url: https://github.com/mrfitzpa/distoptica
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
